#!/bin/bash

echo 'Making mine and tmp directories ...'
cd ~
mkdir tmp mine


echo 'Updates ...'
sudo apt-get update


echo 'Installing git ...'
sudo apt-get install git


echo 'Cloning setupz ...'
cd ~/mine
git clone https://github.com/jehoshua02/setupz.git


cd ~
echo 'Symlink .gitconfig'
ln -s ~/mine/setupz/dotfiles/.gitconfig
echo 'Symlink .gitignore'
ln -s ~/mine/setupz/dotfiles/.gitignore
echo 'Symlink .vimrc'
ln -s ~/mine/setupz/dotfiles/.vimrc


echo 'Include .bash_extras in .bashrc'
echo -e "
# bash extras
if [ -f ~/mine/setupz/dotfiles/.bash_extras ]; then
    . ~/mine/setupz/dotfiles/.bash_extras
fi
" >> ~/.bashrc


echo 'Installing git html help (/usr/share/doc/git/html) ...'
sudo mkdir -p /usr/share/doc/git
cd /usr/share/doc/git
sudo git clone git://git.kernel.org/pub/scm/git/git-htmldocs.git html


echo 'Installing vim ...'
sudo apt-get install vim


echo 'Installing curl ...'
sudo apt-get install curl


echo 'Installing composer ...'
cd ~/tmp
curl -s https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer


echo 'Installing Eclipse IDE ...'
sudo apt-get install eclipse


echo 'Installing LAMP Server ...'
sudo apt-get install lamp-server^


echo 'Installing XDebug ...'
sudo apt-get install php5-xdebug
echo "
xdebug.remote_enable=On
xdebug.remote_handler=dbgp
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.collect_params = 4
" | sudo tee -a /etc/php5/conf.d/xdebug.ini


echo 'Manually install firefox addons:
    + firebug
    + RESTClient
    + easyXDebug
    + flash :P
    + etc.
Manually configure firefox preferences:
    + home page
    + downloads
    + history
    + passwords
    + mailto
    + etc'
firefox -preferences about:addons


echo 'Installing Google Chrome ...'
cd ~/tmp
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb


echo 'Manually configure Google Chrome ...'
google-chrome chrome://chrome/settings/

echo 'Installing compiz config settings manager ...'
sudo apt-get install compizconfig-settings-manager

echo 'Manually configure compiz settings manager:
    + workspaces
    + window resizing
    + resize info
    + launcher icon size
    + wobbly windows
    + negative display
    + etc'
ccsm

echo 'Installing MySQL Workbench ...'
sudo apt-get install mysql-workbench
